# Generated by Django 3.2.16 on 2023-02-26 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_familio_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='stripeCustomerId',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='customuser',
            name='stripeSubscriptionId',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='photo',
            field=models.ImageField(blank=True, default='', null=True, upload_to='static/media/'),
        ),
        migrations.AlterField(
            model_name='familio',
            name='kinship',
            field=models.CharField(choices=[('Mother', 'Mother'), ('Father', 'Father'), ('Brother', 'Brother'), ('Sister', 'Sister'), ('Wife', 'Wife'), ('Husband', 'Husband'), ('Cousin', 'Cousin'), ('Aunt', 'Aunt'), ('Uncle', 'Uncle'), ('Nephew', 'Nephew'), ('Niece', 'Niece'), ('Grandmother', 'Grandmother'), ('Grandfather', 'Grandfather'), ('Great-grandmother', 'Great-grandmother'), ('Great-grandfather', 'Great-grandfather'), ('Brother-in-law', 'Brother-in-law'), ('Sister-in-law', 'Sister-in-law'), ('Mother-in-law', 'Mother-in-law'), ('Father-in-law', 'Father-in-law'), ('Son', 'Son'), ('Daughter', 'Daughter')], max_length=20),
        ),
    ]
