# Generated by Django 3.2.16 on 2023-02-28 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0005_auto_20230226_1401'),
    ]

    operations = [
        migrations.AddField(
            model_name='familio',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
