# Generated by Django 3.2.16 on 2023-02-28 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0006_familio_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='familio',
        ),
        migrations.AddField(
            model_name='group',
            name='familio',
            field=models.ManyToManyField(to='member.Familio'),
        ),
    ]
