# Generated by Django 3.2.16 on 2023-03-01 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0007_auto_20230228_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familio',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
