# Generated by Django 3.2.16 on 2023-03-01 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0009_alter_familio_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='familio',
            name='email',
            field=models.EmailField(blank=True, default='nomail@familio.uk', max_length=254, null=True),
        ),
    ]
