# Generated by Django 3.2.16 on 2023-03-01 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0011_alter_familio_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='member',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='member.customuser'),
            preserve_default=False,
        ),
    ]
